<?php
namespace App\Controllers;

class AdminController {
    private $db;
    public function __construct($db){$this->db=$db;if(session_status()===PHP_SESSION_NONE)session_start();}
    private function json($data,$status=200){http_response_code($status);echo json_encode($data,JSON_UNESCAPED_UNICODE);}
    private function autorizado(){if(empty($_SESSION['usuario_id'])||($_SESSION['usuario_rol']??'')!=='admin'){ $this->json(['status'=>'error','message'=>'Se requiere una sesión de administrador'],401);return false;}return true;}
    public function conversaciones(){if(!$this->autorizado())return;$stmt=$this->db->query('SELECT c.ID_chat AS id,LOWER(c.Tipo_chat) AS tipo,c.Titulo AS etiqueta,c.Descripcion AS descripcion,LOWER(REPLACE(c.Estado,\' \',\'_\')) AS estado,c.Foto AS foto_path,DATE_FORMAT(c.Fecha_hora,"%d/%m/%Y %H:%i") AS creado,p.Nombre AS socio,p.Correo AS email FROM Chat c INNER JOIN Persona p ON p.ID_usuario=c.ID_usuario ORDER BY c.Fecha_hora DESC');$this->json(['status'=>'success','conversaciones'=>$stmt->fetchAll(\PDO::FETCH_ASSOC)]);}
    public function mensajes($id){if(!$this->autorizado())return;$stmt=$this->db->prepare('SELECT m.ID_mensaje AS id,m.Mensaje AS mensaje,m.Fecha_hora AS creado_en,p.Nombre AS nombre FROM Mensajes_chat m INNER JOIN Persona p ON p.ID_usuario=m.ID_usuario WHERE m.ID_chat=:chat ORDER BY m.Fecha_hora');$stmt->execute(['chat'=>(int)$id]);$this->json(['status'=>'success','mensajes'=>$stmt->fetchAll(\PDO::FETCH_ASSOC)]);}
    public function responder($id){if(!$this->autorizado())return;$in=json_decode(file_get_contents('php://input'),true)?:[];$mensaje=trim((string)($in['mensaje']??''));if($mensaje==='')return $this->json(['status'=>'error','message'=>'El mensaje es obligatorio'],400);$stmt=$this->db->prepare('SELECT ID_chat FROM Chat WHERE ID_chat=:chat');$stmt->execute(['chat'=>(int)$id]);if(!$stmt->fetchColumn())return $this->json(['status'=>'error','message'=>'Conversación no encontrada'],404);$stmt=$this->db->prepare('INSERT INTO Mensajes_chat (ID_chat,ID_usuario,Mensaje) VALUES (:chat,:usuario,:mensaje)');$stmt->execute(['chat'=>(int)$id,'usuario'=>(int)$_SESSION['usuario_id'],'mensaje'=>$mensaje]);$this->json(['status'=>'success','message'=>'Respuesta enviada']);}
    public function cambiarEstado($id){if(!$this->autorizado())return;$in=json_decode(file_get_contents('php://input'),true)?:[];$map=['abierto'=>'Abierto','en_revision'=>'En revision','en_reparacion'=>'En reparacion','solucionado'=>'Solucionado'];$estado=$map[trim((string)($in['estado']??''))]??null;if(!$estado)return $this->json(['status'=>'error','message'=>'Estado inválido'],400);$stmt=$this->db->prepare('UPDATE Chat SET Estado=:estado WHERE ID_chat=:chat');$stmt->execute(['estado'=>$estado,'chat'=>(int)$id]);$this->json(['status'=>'success','message'=>'Estado actualizado']);}
    public function resumen(){if(!$this->autorizado())return;$socios=$this->db->query("SELECT u.ID_usuario AS id,p.Nombre AS nombre,p.Correo AS email,u.Activo AS activo,COALESCE((SELECT m.Estado FROM Membresias m WHERE m.ID_usuario=u.ID_usuario ORDER BY m.Fecha_vencimiento DESC LIMIT 1),'Sin membresía') AS membresia,(SELECT m.Fecha_vencimiento FROM Membresias m WHERE m.ID_usuario=u.ID_usuario ORDER BY m.Fecha_vencimiento DESC LIMIT 1) AS vencimiento,(SELECT m.ID_plan FROM Membresias m WHERE m.ID_usuario=u.ID_usuario ORDER BY m.Fecha_vencimiento DESC LIMIT 1) AS plan_id,se.ID_entrenador AS entrenador_id FROM Usuarios u INNER JOIN Persona p ON p.ID_usuario=u.ID_usuario LEFT JOIN Socio_Entrenador se ON se.ID_socio=u.ID_usuario INNER JOIN Tipo_usuario t ON t.ID_tipo=u.ID_tipo WHERE t.Nombre='Socio' ORDER BY p.Nombre")->fetchAll(\PDO::FETCH_ASSOC);$usuarios=$this->db->query("SELECT u.ID_usuario AS id,p.Nombre AS nombre,p.Correo AS email,u.Activo AS activo,t.Nombre AS rol FROM Usuarios u INNER JOIN Persona p ON p.ID_usuario=u.ID_usuario INNER JOIN Tipo_usuario t ON t.ID_tipo=u.ID_tipo ORDER BY u.Activo DESC,p.Nombre")->fetchAll(\PDO::FETCH_ASSOC);$entrenadores=$this->db->query("SELECT u.ID_usuario AS id,p.Nombre AS nombre FROM Usuarios u INNER JOIN Persona p ON p.ID_usuario=u.ID_usuario INNER JOIN Tipo_usuario t ON t.ID_tipo=u.ID_tipo WHERE t.Nombre='Entrenador' AND u.Activo=1 ORDER BY p.Nombre")->fetchAll(\PDO::FETCH_ASSOC);$ejercicios=$this->db->query('SELECT ID_ejercicio AS id,Nombre AS nombre,Grupo_muscular AS grupo_muscular,Activo AS activo FROM Ejercicios ORDER BY Nombre')->fetchAll(\PDO::FETCH_ASSOC);$planes=$this->db->query('SELECT ID_plan AS id,Nombre AS nombre,Precio AS precio FROM Plan WHERE Activo=1 ORDER BY Nombre')->fetchAll(\PDO::FETCH_ASSOC);$this->json(['status'=>'success','socios'=>$socios,'usuarios'=>$usuarios,'entrenadores'=>$entrenadores,'ejercicios'=>$ejercicios,'planes'=>$planes]);}
    public function asignarEntrenador($id){if(!$this->autorizado())return;$in=json_decode(file_get_contents('php://input'),true)?:[];$entrenador=(int)($in['entrenador_id']??0);if($entrenador){$stmt=$this->db->prepare('INSERT INTO Socio_Entrenador (ID_socio,ID_entrenador) VALUES (:socio,:entrenador) ON DUPLICATE KEY UPDATE ID_entrenador=VALUES(ID_entrenador),Fecha_asignacion=NOW()');$stmt->execute(['socio'=>(int)$id,'entrenador'=>$entrenador]);}else{$stmt=$this->db->prepare('DELETE FROM Socio_Entrenador WHERE ID_socio=:socio');$stmt->execute(['socio'=>(int)$id]);}$this->json(['status'=>'success','message'=>'Entrenador actualizado']);}
    public function actualizarMembresia($id){if(!$this->autorizado())return;$in=json_decode(file_get_contents('php://input'),true)?:[];$plan=(int)($in['plan_id']??0);$estado=$in['estado']??'Al dia';$vencimiento=trim((string)($in['vencimiento']??''));if($vencimiento==='')$vencimiento=date('Y-m-t');$permitidos=['Al dia','Vencida','Bloqueada'];if(!$plan||!in_array($estado,$permitidos,true)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$vencimiento))return $this->json(['status'=>'error','message'=>'Datos de membresía inválidos'],400);$stmt=$this->db->prepare('SELECT Precio FROM Plan WHERE ID_plan=:plan');$stmt->execute(['plan'=>$plan]);$precio=$stmt->fetchColumn();if($precio===false)return $this->json(['status'=>'error','message'=>'Plan inexistente'],400);$check=$this->db->prepare('SELECT ID_membresia FROM Membresias WHERE ID_usuario=:usuario ORDER BY Fecha_vencimiento DESC LIMIT 1');$check->execute(['usuario'=>(int)$id]);$membership=$check->fetchColumn();if($membership){$stmt=$this->db->prepare('UPDATE Membresias SET ID_plan=:plan,Fecha_vencimiento=:vencimiento,Estado=:estado,Fecha_ultimo_pago=NOW(),Monto_ultimo_pago=:precio WHERE ID_membresia=:id');$stmt->execute(['plan'=>$plan,'vencimiento'=>$vencimiento,'estado'=>$estado,'precio'=>$precio,'id'=>$membership]);}else{$stmt=$this->db->prepare('INSERT INTO Membresias (ID_usuario,ID_plan,Fecha_inicio,Fecha_vencimiento,Estado,Fecha_ultimo_pago,Monto_ultimo_pago) VALUES (:usuario,:plan,CURRENT_DATE,:vencimiento,:estado,NOW(),:precio)');$stmt->execute(['usuario'=>(int)$id,'plan'=>$plan,'vencimiento'=>$vencimiento,'estado'=>$estado,'precio'=>$precio]);}$this->json(['status'=>'success','message'=>'Membresía actualizada']);}
    public function crearEjercicio(){if(!$this->autorizado())return;$in=json_decode(file_get_contents('php://input'),true)?:[];$nombre=trim((string)($in['nombre']??''));$grupo=trim((string)($in['grupo_muscular']??''));if($nombre===''||$grupo==='')return $this->json(['status'=>'error','message'=>'Nombre y grupo muscular son obligatorios'],400);$stmt=$this->db->prepare('INSERT INTO Ejercicios (Nombre,Grupo_muscular,Descripcion) VALUES (:nombre,:grupo,:descripcion)');try{$stmt->execute(['nombre'=>$nombre,'grupo'=>$grupo,'descripcion'=>trim((string)($in['descripcion']??''))]);$this->json(['status'=>'success','message'=>'Ejercicio agregado']);}catch(\PDOException $error){$this->json(['status'=>'error','message'=>'El ejercicio ya existe'],409);}}
    public function crearUsuario(){if(!$this->autorizado())return;$in=json_decode(file_get_contents('php://input'),true)?:[];$nombre=trim((string)($in['nombre']??''));$email=trim((string)($in['email']??''));$password=(string)($in['password']??'');$rol=(int)($in['rol_id']??0);if($nombre===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<6||!in_array($rol,[1,2,3,4],true))return $this->json(['status'=>'error','message'=>'Nombre, email, contraseña de 6 caracteres y rol válido son obligatorios'],400);try{$this->db->beginTransaction();$stmt=$this->db->prepare('INSERT INTO Usuarios (Usuario,Password,ID_tipo,Activo) VALUES (:email,:password,:rol,1)');$stmt->execute(['email'=>$email,'password'=>password_hash($password,PASSWORD_DEFAULT),'rol'=>$rol]);$usuario=(int)$this->db->lastInsertId();$stmt=$this->db->prepare('INSERT INTO Persona (Nombre,Correo,ID_usuario) VALUES (:nombre,:email,:usuario)');$stmt->execute(['nombre'=>$nombre,'email'=>$email,'usuario'=>$usuario]);$this->db->commit();$this->json(['status'=>'success','message'=>'Usuario creado','id'=>$usuario],201);}catch(\PDOException $error){if($this->db->inTransaction())$this->db->rollBack();$this->json(['status'=>'error','message'=>'El email ya está registrado'],409);}}
    public function actualizarUsuario($id){if(!$this->autorizado())return;$in=json_decode(file_get_contents('php://input'),true)?:[];$nombre=trim((string)($in['nombre']??''));$email=trim((string)($in['email']??''));if($nombre===''||!filter_var($email,FILTER_VALIDATE_EMAIL))return $this->json(['status'=>'error','message'=>'Nombre y email válidos son obligatorios'],400);try{$stmt=$this->db->prepare('UPDATE Persona SET Nombre=:nombre,Correo=:email WHERE ID_usuario=:usuario');$stmt->execute(['nombre'=>$nombre,'email'=>$email,'usuario'=>(int)$id]);$stmt=$this->db->prepare('UPDATE Usuarios SET Usuario=:email WHERE ID_usuario=:usuario');$stmt->execute(['email'=>$email,'usuario'=>(int)$id]);$this->json(['status'=>'success','message'=>'Usuario actualizado']);}catch(\PDOException $error){$this->json(['status'=>'error','message'=>'No se pudo actualizar el usuario'],409);}}
    public function desactivarUsuario($id){if(!$this->autorizado())return;$stmt=$this->db->prepare('UPDATE Usuarios SET Activo=0 WHERE ID_usuario=:usuario AND ID_usuario<>:admin');$stmt->execute(['usuario'=>(int)$id,'admin'=>(int)$_SESSION['usuario_id']]);$this->json(['status'=>'success','message'=>'Usuario dado de baja']);}
}
