<?php
namespace App\Controllers;

class PersonalController {
    private $db;
    public function __construct($db){$this->db=$db;if(session_status()===PHP_SESSION_NONE)session_start();}
    private function json($data,$status=200){http_response_code($status);echo json_encode($data,JSON_UNESCAPED_UNICODE);}
    private function autorizado(){if(empty($_SESSION['usuario_id'])||($_SESSION['usuario_rol']??'')!=='personal'){$this->json(['status'=>'error','message'=>'Se requiere una sesión de personal'],401);return false;}return true;}
    public function conversaciones(){if(!$this->autorizado())return;$stmt=$this->db->query("SELECT c.ID_chat AS id,c.Titulo AS etiqueta,c.Descripcion AS descripcion,LOWER(REPLACE(c.Estado,' ','_')) AS estado,DATE_FORMAT(c.Fecha_hora,'%d/%m/%Y %H:%i') AS creado,p.Nombre AS socio FROM Chat c INNER JOIN Persona p ON p.ID_usuario=c.ID_usuario WHERE c.Tipo_chat='Mantenimiento' ORDER BY FIELD(c.Estado,'Abierto','En revision','En reparacion','Solucionado'),c.Fecha_hora DESC");$this->json(['status'=>'success','conversaciones'=>$stmt->fetchAll(\PDO::FETCH_ASSOC)]);}
    public function mensajes($id){if(!$this->autorizado())return;$stmt=$this->db->prepare('SELECT m.Mensaje AS mensaje,m.Fecha_hora AS creado,p.Nombre AS nombre FROM Mensajes_chat m INNER JOIN Persona p ON p.ID_usuario=m.ID_usuario WHERE m.ID_chat=:chat ORDER BY m.Fecha_hora');$stmt->execute(['chat'=>(int)$id]);$this->json(['status'=>'success','mensajes'=>$stmt->fetchAll(\PDO::FETCH_ASSOC)]);}
    public function responder($id){if(!$this->autorizado())return;$in=json_decode(file_get_contents('php://input'),true)?:[];$mensaje=trim((string)($in['mensaje']??''));if($mensaje==='')return $this->json(['status'=>'error','message'=>'El mensaje es obligatorio'],400);$stmt=$this->db->prepare('SELECT ID_chat FROM Chat WHERE ID_chat=:chat AND Tipo_chat="Mantenimiento"');$stmt->execute(['chat'=>(int)$id]);if(!$stmt->fetchColumn())return $this->json(['status'=>'error','message'=>'Reporte no encontrado'],404);$stmt=$this->db->prepare('INSERT INTO Mensajes_chat (ID_chat,ID_usuario,Mensaje) VALUES (:chat,:usuario,:mensaje)');$stmt->execute(['chat'=>(int)$id,'usuario'=>(int)$_SESSION['usuario_id'],'mensaje'=>$mensaje]);$this->json(['status'=>'success','message'=>'Respuesta enviada']);}
    public function cambiarEstado($id){if(!$this->autorizado())return;$in=json_decode(file_get_contents('php://input'),true)?:[];$map=['abierto'=>'Abierto','en_revision'=>'En revision','en_reparacion'=>'En reparacion','solucionado'=>'Solucionado'];$estado=$map[$in['estado']??'']??null;if(!$estado)return $this->json(['status'=>'error','message'=>'Estado inválido'],400);$stmt=$this->db->prepare('UPDATE Chat SET Estado=:estado,ID_personal=:personal WHERE ID_chat=:chat AND Tipo_chat="Mantenimiento"');$stmt->execute(['estado'=>$estado,'personal'=>(int)$_SESSION['usuario_id'],'chat'=>(int)$id]);$this->json(['status'=>'success','message'=>'Estado actualizado']);}
}
